# Adapted from docker4drupal.
# See https://docker4drupal.readthedocs.io/en/latest/
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_MAX_ALLOWED_PACKET: 2G
    volumes:
      - ./docker-info/mariadb-init:/docker-entrypoint-initdb.d

  php:
    image: wodby/drupal-php:7.1-3.0.0
    environment:
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}8"
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./d8:/var/www/html:cached
      - ~/.ssh:/home/www-data/.ssh
      - ~/.drush/site-aliases:/home/www-data/.drush/site-aliases
      - ~/.drush/sites:/home/www-data/.drush/sites

  nginx:
    image: wodby/drupal-nginx:8-1.13-3.0.1
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    labels:
      - "traefik.backend=nginx"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}8.docker.localhost"
    volumes:
      - ./d8:/var/www/html:cached

  mariadb7:
    image: wodby/mariadb:10.1-2.3.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      MYSQL_MAX_ALLOWED_PACKET: 2G
    volumes:
      - ./docker-info/mariadb7-init:/docker-entrypoint-initdb.d

  php7:
    image: wodby/drupal-php:5.6-3.3.1
    environment:
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      COMPOSE_PROJECT_NAME: "${COMPOSE_PROJECT_NAME}7"
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      PHP_TIMEZONE: "America/Chicago"
    volumes:
      - ./d7:/var/www/html:cached
      - ~/.ssh:/home/www-data/.ssh
      - ~/.drush/site-aliases:/home/www-data/.drush/site-aliases
      - ~/.drush/sites:/home/www-data/.drush/sites

  nginx7:
    image: wodby/drupal-nginx:7-1.13-3.0.2
    depends_on:
      - php7
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php7
      NGINX_SERVER_ROOT: /var/www/html/docroot
      #NGINX_DRUPAL_FILE_PROXY_URL: "http://${COMPOSE_PROJECT_NAME}7.docker.localhost:8080"
    labels:
      - "traefik.backend=nginx7"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:${COMPOSE_PROJECT_NAME}7.docker.localhost"
    volumes:
      - ./d7:/var/www/html:cached

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - "traefik.frontend.rule=Host:mailhog.${COMPOSE_PROJECT_NAME}.docker.localhost"

  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - "traefik.frontend.rule=Host:portainer.${COMPOSE_PROJECT_NAME}.docker.localhost"

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '8000:80'
